name: Django CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build test image
        run: |
          docker build -f backend.test.Dockerfile \
            -t ghcr.io/anna-fritz/videoflix-backend/backend-test:latest .

      - name: Push test image
        run: docker push ghcr.io/anna-fritz/videoflix-backend/backend-test:latest

      - name: Run test container
        env:
          TEST_IMAGE: ghcr.io/anna-fritz/videoflix-backend/backend-test:latest
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          docker compose -f docker-compose.test.yml up --exit-code-from test
          docker compose -f docker-compose.test.yml down -v

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build release image
        run: docker compose -f docker-compose.prod.yml build web

      - name: Push release image
        run: docker push ghcr.io/anna-fritz/videoflix-backend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_APP_PATH }}
            docker pull ghcr.io/anna-fritz/videoflix-backend:latest
            docker compose -f docker-compose.prod.yml up -d --force-recreate