name: Django CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test image
        run: |
          REPO=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          docker build -f backend.test.Dockerfile \
            -t ghcr.io/$REPO/backend-test:latest .

      - name: Push test image
        run: docker push ghcr.io/$REPO/backend-test:latest

      - name: Create .env.test file
        run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env.test

      - name: Run test container
        run: docker run --rm --env-file .env.test ghcr.io/${{ github.repository }}/backend-test:latest