name: Django CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build test image
        run: |
          docker build -f backend.test.Dockerfile \
            -t ghcr.io/anna-fritz/videoflix-backend/backend-test:latest .

      - name: Push test image
        run: docker push ghcr.io/anna-fritz/videoflix-backend/backend-test:latest

      - name: Create .env.test file
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env.test
          echo "POSTGRES_HOST=db" >> .env.test
          echo "POSTGRES_PORT=5432" >> .env.test
          echo "REDIS_HOST=redis" >> .env.test
          echo "REDIS_PORT=6379" >> .env.test

      - name: Run test container
        run: |
          TEST_IMAGE=ghcr.io/anna-fritz/videoflix-backend/backend-test:latest
          docker compose run --rm --env-file .env.test test